// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mg_project
Rcpp::DataFrame mg_project(NumericVector x, NumericVector y, std::string proj_string, bool inverse);
RcppExport SEXP _meteogrid4_mg_project(SEXP xSEXP, SEXP ySEXP, SEXP proj_stringSEXP, SEXP inverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type proj_string(proj_stringSEXP);
    Rcpp::traits::input_parameter< bool >::type inverse(inverseSEXP);
    rcpp_result_gen = Rcpp::wrap(mg_project(x, y, proj_string, inverse));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_meteogrid4_mg_project", (DL_FUNC) &_meteogrid4_mg_project, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_meteogrid4(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
