# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

proj_version <- function() {
    .Call('_meteogrid4_proj_version', PACKAGE = 'meteogrid4')
}

mg_project <- function(x, y, proj_string, inverse = FALSE) {
    .Call('_meteogrid4_mg_project', PACKAGE = 'meteogrid4', x, y, proj_string, inverse)
}

upscale_by_mean <- function(px, py, pval, gnx, gny) {
    .Call('_meteogrid4_upscale_by_mean', PACKAGE = 'meteogrid4', px, py, pval, gnx, gny)
}

